# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/liteDRAM.xdc

# XDC: imports/src/rvfpga.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_0 || ORIG_REF_NAME==BD_bidirec_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_1 || ORIG_REF_NAME==BD_bidirec_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_2 || ORIG_REF_NAME==BD_bidirec_0_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_3/BD_bidirec_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_3 || ORIG_REF_NAME==BD_bidirec_0_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_4/BD_bidirec_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_4 || ORIG_REF_NAME==BD_bidirec_0_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_5/BD_bidirec_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_5 || ORIG_REF_NAME==BD_bidirec_0_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_6/BD_bidirec_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_6 || ORIG_REF_NAME==BD_bidirec_0_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_7/BD_bidirec_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_7 || ORIG_REF_NAME==BD_bidirec_0_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_8/BD_bidirec_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_8 || ORIG_REF_NAME==BD_bidirec_0_8} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_9/BD_bidirec_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_9 || ORIG_REF_NAME==BD_bidirec_0_9} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_10/BD_bidirec_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_10 || ORIG_REF_NAME==BD_bidirec_0_10} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_11/BD_bidirec_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_11 || ORIG_REF_NAME==BD_bidirec_0_11} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_12/BD_bidirec_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_12 || ORIG_REF_NAME==BD_bidirec_0_12} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_13/BD_bidirec_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_13 || ORIG_REF_NAME==BD_bidirec_0_13} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_14/BD_bidirec_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_14 || ORIG_REF_NAME==BD_bidirec_0_14} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_15/BD_bidirec_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_15 || ORIG_REF_NAME==BD_bidirec_0_15} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_16/BD_bidirec_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_16 || ORIG_REF_NAME==BD_bidirec_0_16} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_17/BD_bidirec_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_17 || ORIG_REF_NAME==BD_bidirec_0_17} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_18/BD_bidirec_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_18 || ORIG_REF_NAME==BD_bidirec_0_18} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_19/BD_bidirec_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_19 || ORIG_REF_NAME==BD_bidirec_0_19} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_20/BD_bidirec_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_20 || ORIG_REF_NAME==BD_bidirec_0_20} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_21/BD_bidirec_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_21 || ORIG_REF_NAME==BD_bidirec_0_21} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_22/BD_bidirec_0_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_22 || ORIG_REF_NAME==BD_bidirec_0_22} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_23/BD_bidirec_0_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_23 || ORIG_REF_NAME==BD_bidirec_0_23} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_24/BD_bidirec_0_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_24 || ORIG_REF_NAME==BD_bidirec_0_24} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_25/BD_bidirec_0_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_25 || ORIG_REF_NAME==BD_bidirec_0_25} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_26/BD_bidirec_0_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_26 || ORIG_REF_NAME==BD_bidirec_0_26} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_27/BD_bidirec_0_27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_27 || ORIG_REF_NAME==BD_bidirec_0_27} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_28/BD_bidirec_0_28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_28 || ORIG_REF_NAME==BD_bidirec_0_28} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_29/BD_bidirec_0_29.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_29 || ORIG_REF_NAME==BD_bidirec_0_29} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_30/BD_bidirec_0_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_30 || ORIG_REF_NAME==BD_bidirec_0_30} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_31/BD_bidirec_0_31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_31 || ORIG_REF_NAME==BD_bidirec_0_31} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
